west:
  url: https://github.com/zephyrproject-rtos/west
  revision: v0.6.0

manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
    - name: armmbed
      url-base: https://github.com/ARMmbed

  projects:
    - name: fw-nrfconnect-zephyr
      path: zephyr
      west-commands: scripts/west-commands.yml
      revision: 1c3a001f62e6c51693b67e4f7ee7f66111d31801
    - name: fw-nrfconnect-nrf
      path: nrf
      revision: f99a3a56ac0204c985117c201ac37b050cf6db08
    - name: nrfxlib
      path: nrfxlib
      revision: 35120d32233dc354c89d8c62eaa6267093c7e35b
    - name: fw-nrfconnect-mcuboot
      path: mcuboot
      revision: 0c59d5f4bb2de49b5491b018fc7fd41afc154f1b
    - name: mbedtls
      repo-path: fw-nrfconnect-mbedtls
      path: modules/crypto/mbedtls
      revision: 900c7eea92e45adba1067e044ec705d4541c84a5
    - name: mbedtls-nrf
      path: mbedtls
      repo-path: mbedtls
      revision: mbedtls-2.13.1
      remote: armmbed
